### ISSUE TITLE
What about database tracking?

### ISSUE THREAD

**Issue by toprak** [JipFr/Adolla#14]
I mean like kitsu, mal etc.

**Comment by JipFr** [comment]
I've never actually used MAL or Kitsu — what do you mean, exactly?

**Comment by toprak** [comment]
I mean, they are database sites also tracking for anime and manga, I mean If adolla had automatically add read chapter from adolla  to mal or kitsu.

**Comment by JipFr** [comment]
Does MAL allow manga? I'm quickly looking at it and it seems like it's just anime.
￼
I also just looked at Kitsu, and I don't see any chapter-specific "read" options there, either.

Am I missing something?

**Comment by toprak** [comment]
We can call them manga keep tracking service like listing not reading service. That's why I called database website them, I mean I opened the issue because I do not know that you know it but there are manga reader like Tachiyomi it lets you read manga and also support automatically synchronize between database. Hope it is clear

**Comment by JipFr** [comment]
It turns out MAL does not have a public API. It would be possible to reverse engineer it, but I would prefer to use public APIs.

Kitsu apparently has a great public API, however, I can't seem to find a place to mark a chapter as "read". Am I missing something here?
![Kitsu](https://user-images.githubusercontent.com/17685409/103415503-a0c48f00-4b82-11eb-87d8-c2323196ee01.png)

Also, if you don't mind, I'm curious. How did you find out about this project?

**Comment by JipFr** [comment]
After looking some more, it turns out Kitsu allows you to tell it how many chapters you have read. It doesn't let you mark individual chapters, which is annoying; any idea how that would work? What if I decide to skip 10?

**Comment by toprak** [comment]
I found out this project while browsing github with "manga-reader" tag and wanted to give a try, it is really nice project brother. there is 2 way about mark chapters, first one is using quick update section when you hover over the a manga it lets you to mark chapter as read I will provide example. Also you can go library and go to a specific manga and click edit this entry, you can increase or decrease progress one by one.
![image](https://user-images.githubusercontent.com/43301560/103419215-1dfffc00-4ba3-11eb-9dff-22bd52f083b8.png) this is quick manga update section.
![image](https://user-images.githubusercontent.com/43301560/103419269-5b648980-4ba3-11eb-8833-413f68108c9b.png)
this is the edit entries section.
Personally I recommend you to add kitsu if you gonna add one because kitsu has more larger manga database than MAL

**Comment by JipFr** [comment]
What happens if you decide to skip the first X chapters? For Shingeki no Kyojin, I first watched the anime and picked up the manga where the anime left off. 

Adolla allows you to read any chapter you wish. Would it take the number of chapters you've read, then submit that? Or, is there a way to make it clear to Kitsu that you did not read the first 80 or so chapters?

Personally, I'd be fine with just the number of chapters you've read. It wouldn't be perfect, but it would give some idea of how much you've read — even if it's not _what_ you've read.

Thoughts?

**Comment by toprak** [comment]
If you skip you can just write progress which chapter do you read, like I read first 30 chapters of aot after then did watch anime and decided to go on with manga and I just write there 82 because im gonna continue on this chapter. I think you should do as you said, number of chapter and submit the number should be nice. I have bad grammar, so if it is not clear please ask again :D
For example, you did read 122th chapter of aot, just submit to 122 number to progress section is what I am wanting :D

**Comment by toprak** [comment]
I also recommend to add Manganelo and Toonily for future, Toonily has really large manhwa(korean) library, Manganelo or mangakakalot just for alternativing MangaDex and MangaSee.

**Comment by toprak** [comment]
By the way I got secret-config in Adolla folder but it can not detect it i guess.

**Comment by JipFr** [comment]
The secret config is to be placed in src/, not the root.

I'll get back to you on the others!

**Comment by JipFr** [comment]
You can receive Telegram notifications by making a bot account on Telegram (message @botfather), get its ID, then put that in. You can then send your bot a message, and the console will show your ID: put that in the config as well.

Then, if you have read the last chapter on a series and a new one comes out, it will send you a message.

**Comment by toprak** [comment]
I am not experienced at all will give a shot. It still does not see my secret-config

**Comment by JipFr** [comment]
Do you have a file called `secret-config.json` in the `src` folder, and then restart the process?

**Comment by toprak** [comment]
Yes

**Comment by JipFr** [comment]
Are you getting any errors? Does it mention there's no secret-config or anything?

**Comment by toprak** [comment]
Yup
>>[SECRET] No secret-config provided.
[SECRET] No mangadex credentials provided in secret-config. Search will be disabled.

**Comment by JipFr** [comment]
I'm not sure what the issue is. Would it be possible to set up a live share session in VSCode, so I can try and find it? Are you on Discord?

I think the most likely perpetrator is the `path` variable in secretConfig.ts, perhaps you could try logging that and seeing if that's correct. If that's not where the issue is, let me know about the Discord thing.

**Comment by toprak** [comment]
I'm kinda busy now if you are free tomorrow i will give my discord maybe we can fix it on dc

**Comment by JipFr** [comment]
Sounds good, add me when you can! Jip#9051

**Comment by JipFr** [comment]
Happy new year, by the way!

**Comment by toprak** [comment]
In Turkey, last 6 min to new year, you too my friend!

**Comment by toprak** [comment]
Man, I could not find any spare time sorry about that. Will you free on sunday? By the way Kitsu is down. I already had to wait sunday.

**Comment by toprak** [comment]
By the way, I had not seen your project has already list stuff. Damn, your project would be better than any database website because we can think it as local database wow. I think there is no need to add Kitsu if you have not already. It would be more better adding other websites like toonily(korean manga), manganel(alternativing mangadex and mangasee) and some nhentai for some pervy users :D

**Comment by farahnur42** [comment]
I'm not sure if I should comment here on an already closed issue but another alternative for the tracking provider is AniList, which has a well-defined (and so far very stable) API. Docs for the API here: https://github.com/AniList/ApiV2-GraphQL-Docs. So far AniList has worked very well for everything I've used it for (Tachiyomi, Neko, MAL-Sync) and better than either MAL (which suffers from ridiculously outdated database policies) or Kitsu (which suffers from stability issues and bugs in general).

BTW MAL *does* have a Public API now but it is very much not feature complete nor fully stable, here are the docs for that: https://myanimelist.net/apiconfig/references/api/v2 and for authorization: https://myanimelist.net/apiconfig/references/authorization. One thing to keep in mind here is that you will need to log in to have access to these docs, so they're not *quite* as easily accessible as say the AniList API docs.

If for example you want to see "reference" implementations of these APIs you can peruse the MAL-Sync, Tachiyomi or Neko repos which are all available on Github under their respective names.
